/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-10-17 12:18:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1697455750871L));
    _jspx_dependants.put("jar:file:/C:/workspace/7_Framework/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LAGC_project/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>메인 페이지</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/common/mainPage.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("@import\r\n");
      out.write("	url('https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap')\r\n");
      out.write("	;\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("  @import url('https://fonts.googleapis.com/css2?family=Aref+Ruqaa&family=Asap:ital,wght@1,600&family=Nanum+Myeongjo:wght@700&family=Noto+Sans+KR:wght@200&family=Rubik+Iso&display=swap');\r\n");
      out.write("</style>\r\n");
      out.write("<style>\r\n");
      out.write("  @import url('https://fonts.googleapis.com/css2?family=Anton&family=Asap:ital,wght@1,600&family=Exo+2:wght@600&family=Exo:wght@700&family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&family=Qwitcher+Grypen:wght@400;700&family=Source+Code+Pro:ital,wght@1,900&display=swap');\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- 메인페이지 최상단 -->\r\n");
      out.write("	<section id=\"main-container\">\r\n");
      out.write("		<img id=\"mainPage-img\" src=\"/resources/img/덕수궁 2.png\">\r\n");
      out.write("		<section id=\"title-container\">\r\n");
      out.write("			<span class=\"black-text\">\"</span> <span class=\"white-text\">TRAVEL</span>\r\n");
      out.write("			<span class=\"black-text\">KOREA</span> <span class=\"white-text\">\"</span>\r\n");
      out.write("		</section>\r\n");
      out.write("		\r\n");
      out.write("		<a href=\"#shortcut-recommend-place-btn\">\r\n");
      out.write("			<button id=\"mainPage-btn1\">	추천	여행지 보러 가기</button>\r\n");
      out.write("		</a>\r\n");
      out.write("				\r\n");
      out.write("		<button type=\"button\">\r\n");
      out.write("			<img id=\"infoBtn\" src=\"/resources/img/이용방법 버튼.png\">\r\n");
      out.write("		</button>\r\n");
      out.write("		\r\n");
      out.write("		<a	href=\"#shortcut-region-place-btn\">\r\n");
      out.write("			<button id=\"mainPage-btn2\">지역별 여행지 보러 가기</button>\r\n");
      out.write("		</a> \r\n");
      out.write("		\r\n");
      out.write("		<a href=\"#main-container\"\r\n");
      out.write("			><img id=\"topBtn\"	src=\"/resources/img/탑버튼.png\">\r\n");
      out.write("		</a>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- 메인페이지 추천 여행지 -->\r\n");
      out.write("	<div id=\"shortcut-recommend-place-btn\"></div>\r\n");
      out.write("	<section id=\"recommend-place\">추천 여행지</section>\r\n");
      out.write("	<section id=\"category-menu\">\r\n");
      out.write("		<section class=\"category-empty\"></section>\r\n");
      out.write("\r\n");
      out.write("		<section class=\"category\">\r\n");
      out.write("			<button class=\"dropbtn\">연령별</button>\r\n");
      out.write("			<div class=\"dropdown-category\">\r\n");
      out.write("				<a href=\"#\">20대</a> <a href=\"#\">30대</a> <a href=\"#\">40대</a> <a\r\n");
      out.write("					href=\"#\">50대 이상</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<section class=\"category\">\r\n");
      out.write("			<button class=\"dropbtn\">구성원별</button>\r\n");
      out.write("			<div class=\"dropdown-category\">\r\n");
      out.write("				<a href=\"#\">혼자</a> <a href=\"#\">친구</a> <a href=\"#\">연인</a> <a href=\"#\">가족</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<section class=\"category\">\r\n");
      out.write("			<button class=\"dropbtn\">계절별</button>\r\n");
      out.write("			<div class=\"dropdown-category\">\r\n");
      out.write("				<a href=\"#\">봄</a> <a href=\"#\">여름</a> <a href=\"#\">가을</a> <a href=\"#\">겨울</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<section class=\"category\">\r\n");
      out.write("			<button class=\"dropbtn\">테마별</button>\r\n");
      out.write("			<div class=\"dropdown-category\">\r\n");
      out.write("				<a href=\"#\">바다</a> <a href=\"#\">도심</a> <a href=\"#\">전통</a> <a href=\"#\">힐링</a>\r\n");
      out.write("				<a href=\"#\">액티비티</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<section class=\"category-empty\"></section>\r\n");
      out.write("	</section>\r\n");
      out.write("	<section id=\"recommend-img\">\r\n");
      out.write("		<section class=\"recommend-empty\"></section>\r\n");
      out.write("		<img src=\"/resources/img/추천1.png\"> <img src=\"/resources/img/추천2.png\">\r\n");
      out.write("		<section class=\"recommend-empty\"></section>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- 메인페이지 지역별 여행지 -->\r\n");
      out.write("	<div id=\"shortcut-region-place-btn\"></div>\r\n");
      out.write("	<section id=\"region-place\">지역별 여행지</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- 서울 -->\r\n");
      out.write("	<section class=\"region-place-btn\">\r\n");
      out.write("		<div id=\"button-magin\"></div>\r\n");
      out.write("		<a href=\"/content/detail?area=seo\"><button class=\"region-btn\">서울</button></a>\r\n");
      out.write("	</section>\r\n");
      out.write("	<section class=\"region-place\">\r\n");
      out.write("		<div class=\"region-empty\"></div>\r\n");
      out.write("		<div id=\"testContent\">\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/서울 추천 콘텐츠 1.png\">\r\n");
      out.write("			<p>여의도 한강공원</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/서울 추천 콘텐츠 2.png\">\r\n");
      out.write("			<p>남산타워</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/서울 추천 콘텐츠 3.png\">\r\n");
      out.write("			<p>서울식물원</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/서울 추천 콘텐츠 4.png\">\r\n");
      out.write("			<p>올림픽공원</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"region-empty\"></div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- 경기 / 인천 -->\r\n");
      out.write("	<section class=\"region-place-btn\">\r\n");
      out.write("		<div id=\"button-magin\"></div>\r\n");
      out.write("		<a href=\"/content/detail?area=gyeinc\"><button class=\"region-btn\">경기 / 인천</button></a>\r\n");
      out.write("	</section>\r\n");
      out.write("	<section class=\"region-place\">\r\n");
      out.write("		<div class=\"region-empty\"></div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/경기 인천 추천 콘텐츠 1.png\">\r\n");
      out.write("			<p>애버랜드</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/경기 인천 추천 콘텐츠 2.png\">\r\n");
      out.write("			<p>캐리비안 베이</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/경기 인천 추천 콘텐츠 3.png\">\r\n");
      out.write("			<p>한국민속촌</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/경기 인천 추천 콘텐츠 4.png\">\r\n");
      out.write("			<p>광명 동굴</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"region-empty\"></div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- 강원 -->\r\n");
      out.write("	<section class=\"region-place-btn\">\r\n");
      out.write("		<div id=\"button-magin\"></div>\r\n");
      out.write("		<a href=\"/content/detail?area=gan\"><button class=\"region-btn\">강원</button></a>\r\n");
      out.write("	</section>\r\n");
      out.write("	<section class=\"region-place\">\r\n");
      out.write("		<div class=\"region-empty\"></div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/강원 추천 콘텐츠 1.png\">\r\n");
      out.write("			<p>정동진 모래시계공원</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/강원 추천 콘텐츠 2.png\">\r\n");
      out.write("			<p>설악산</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/강원 추천 콘텐츠 3.png\">\r\n");
      out.write("			<p>대관령 하늘목장</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/강원 추천 콘텐츠 4.png\">\r\n");
      out.write("			<p>영금정</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"region-empty\"></div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- 충청 -->\r\n");
      out.write("	<section class=\"region-place-btn\">\r\n");
      out.write("		<div id=\"button-magin\"></div>\r\n");
      out.write("		<a href=\"/content/detail?area=chu\"><button class=\"region-btn\">충청</button></a>\r\n");
      out.write("	</section>\r\n");
      out.write("	<section class=\"region-place\">\r\n");
      out.write("		<div class=\"region-empty\"></div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/충청 추천 콘텐츠 1.png\">\r\n");
      out.write("			<p>탑평리</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\"  src=\"/resources/img/충청 추천 콘텐츠 2.png\">\r\n");
      out.write("			<p>대청호</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/충청 추천 콘텐츠 3.png\">\r\n");
      out.write("			<p>청남대</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/충청 추천 콘텐츠 4.png\">\r\n");
      out.write("			<p>만리포 해수욕장</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"region-empty\"></div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- 전라 -->\r\n");
      out.write("	<section class=\"region-place-btn\">\r\n");
      out.write("		<div id=\"button-magin\"></div>\r\n");
      out.write("		<a href=\"/content/detail?area=jeo\"><button class=\"region-btn\">전라</button></a>\r\n");
      out.write("	</section>\r\n");
      out.write("	<section class=\"region-place\">\r\n");
      out.write("		<div class=\"region-empty\"></div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/전라 추천 콘텐츠 1.png\">\r\n");
      out.write("			<p>여수 해상케이블카</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/전라 추천 콘텐츠 2.png\">\r\n");
      out.write("			<p>오동도</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/전라 추천 콘텐츠 3.png\">\r\n");
      out.write("			<p>여수 아쿠아플라넷</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/전라 추천 콘텐츠 4.png\">\r\n");
      out.write("			<p>섬진강 기차마을</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"region-empty\"></div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- 경상 -->\r\n");
      out.write("	<section class=\"region-place-btn\">\r\n");
      out.write("		<div id=\"button-magin\"></div>\r\n");
      out.write("		<a href=\"/content/detail?area=gye\"><button class=\"region-btn\">경상</button></a>\r\n");
      out.write("	</section>\r\n");
      out.write("	<section class=\"region-place\">\r\n");
      out.write("		<div class=\"region-empty\"></div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/경상 추천 콘텐츠 1.png\">\r\n");
      out.write("			<p>해동용궁사</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/경상 추천 콘텐츠 2.png\">\r\n");
      out.write("			<p>포항 스페이스 워크</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/경상 추천 콘텐츠 3.png\">\r\n");
      out.write("			<p>감천 문화마을</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/경상 추천 콘텐츠 4.png\">\r\n");
      out.write("			<p>호미곶 해맞이광장</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"region-empty\"></div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- 제주 -->\r\n");
      out.write("	<section class=\"region-place-btn\">\r\n");
      out.write("		<div id=\"button-magin\"></div>\r\n");
      out.write("		<a href=\"/content/detail?area=jej\"><button class=\"region-btn\">제주</button></a>\r\n");
      out.write("	</section>\r\n");
      out.write("	<section class=\"region-place\">\r\n");
      out.write("		<div class=\"region-empty\"></div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/제주 추천 콘텐츠 1.png\">\r\n");
      out.write("			<p>오설록 티뮤지엄</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/제주 추천 콘텐츠 2.png\">\r\n");
      out.write("			<p>동백포레스트</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/제주 추천 콘텐츠 3.png\">\r\n");
      out.write("			<p>협재 해수욕장</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img class=\"place-move-motion\" src=\"/resources/img/제주 추천 콘텐츠 4.png\">\r\n");
      out.write("			<p>만장굴</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"region-empty\"></div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<div style=\"height: 300px\"></div>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/howToUse.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/content/popup.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
